name: example
description: An example project for demonstration of usage of web_browser_detect.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

  web_browser_detect:
    path: ../

flutter:
  uses-material-design: true
